# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: paper_manager_db
    hostname: postgres
    ports: 
      - 5432:5432

  pgadmin4:
    build: ./pgadmin4
    restart: always
    hostname: pgadmin
    ports:
      - 80:80
    environment: 
        PGADMIN_DEFAULT_EMAIL: 'admin@domain.com'
        PGADMIN_DEFAULT_PASSWORD: admin

