######################################################################
# Automatically generated by qmake (3.1) Sun Apr 30 14:15:34 2023
######################################################################

TEMPLATE = app
INCLUDEPATH += .

QT += core gui widgets

SOURCES += \
    main.cpp \

# Directories
