/*
DROP TABLE IF EXISTS AUTHOR CASCADE;
DROP TABLE IF EXISTS PUBLICATION CASCADE;
DROP TABLE IF EXISTS COMPILATION CASCADE;
DROP TABLE IF EXISTS PUBLISHER CASCADE;
DROP TABLE IF EXISTS PUBLICATION_AUTHORS CASCADE;
DROP TABLE IF EXISTS COMPILATION_ENTRY CASCADE;
*/
CREATE TABLE AUTHOR (
	authorID SERIAL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	degree VARCHAR(30)
);
CREATE TABLE PUBLISHER(
	publisherID SERIAL PRIMARY KEY,
	fullName VARCHAR(200) NOT NULL,
	abbreviation VARCHAR(30),
	country VARCHAR(100),
	city VARCHAR(100),
	address VARCHAR(100),
	phoneNumber VARCHAR(13),
	email VARCHAR(100)
);
CREATE TABLE PUBLICATION(
	publicationID SERIAL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	type SMALLINT NOT NULL,
	publicationDate DATE,
	publisherID INT NOT NULL,
	CONSTRAINT fk_publisherID FOREIGN KEY(publisherID) REFERENCES PUBLISHER(publisherID)
		ON DELETE SET NULL 
);
CREATE TABLE COMPILATION(
	compilationID SERIAL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	publisherID INT NOT NULL,
	publicationDate DATE,
	CONSTRAINT fk_publisherID FOREIGN KEY(publisherID) REFERENCES PUBLISHER(publisherID)
		ON DELETE CASCADE 
);
CREATE TABLE PUBLICATION_AUTHORS(
	publicationID INT NOT NULL,
	authorID INT NOT NULL,
	CONSTRAINT fk_publicationID FOREIGN KEY(publicationID) REFERENCES PUBLICATION(publicationID)
		ON DELETE CASCADE,
	CONSTRAINT fk_authorID FOREIGN KEY(authorID) REFERENCES AUTHOR(authorID)
		ON DELETE CASCADE
);
CREATE TABLE COMPILATION_ENTRY(
	publicationID INT NOT NULL,
	compilationID INT NOT NULL,
	CONSTRAINT fk_publicationID FOREIGN KEY(publicationID) REFERENCES PUBLICATION(publicationID)
		ON DELETE CASCADE,
	CONSTRAINT fk_compilationID FOREIGN KEY(compilationID) REFERENCES COMPILATION(compilationID)
		ON DELETE CASCADE
);