CREATE USER viewer WITH PASSWORD 'viewer';
CREATE USER editor WITH PASSWORD 'editor';
CREATE ROLE viewer_role;
CREATE ROLE editor_role IN ROLE viewer_role;
GRANT viewer_role TO viewer;
GRANT editor_role TO editor;

GRANT SELECT ON TABLE 
	PUBLISHER, PUBLICATION, AUTHOR, COMPILATION, PUBLICATION_AUTHORS, COMPILATION_ENTRY,
	PUBLICATION_COMPOSITE,
	COMPILATION_COMPOSITE,
	AUTHOR_COMPOSITE
TO viewer_role;
GRANT EXECUTE ON FUNCTION 
	get_publication_authors,
	get_publication_compilations,
	get_authors_publications
TO viewer_role;

GRANT ALL PRIVILEGES ON TABLE 
	PUBLISHER, PUBLICATION, AUTHOR, COMPILATION, PUBLICATION_AUTHORS, COMPILATION_ENTRY,
	PUBLICATION_COMPOSITE,
	COMPILATION_COMPOSITE,
	AUTHOR_COMPOSITE
TO editor_role;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO editor_role;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO editor_role;

